services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./certs:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:9080"  # Изменено на 9081
      - "9444:9443"
    environment:
      - API_SPARK_DOMAIN=elt.resoleasing.com
    command: nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: .
    ports:
      - "9080:9080"
    volumes:
      - .:/opt/app
    command: bash -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 9080"
    env_file:
      - .env
    depends_on:
      elt_db:
        condition: service_healthy

  elt_db:
    image: postgres
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5