"""Added InsuranceElt Table

Revision ID: cca46de85dbf
Revises: 
Create Date: 2024-12-05 12:06:28.156172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cca46de85dbf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurance_elt",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("insurance_id", sa.Integer(), nullable=False),
        sa.Column("insurance_name", sa.Text(), nullable=False),
        sa.Column("RequestId", sa.String(), nullable=False),
        sa.Column("SKCalcId", sa.String(), nullable=True),
        sa.Column("Message", sa.Text(), nullable=True),
        sa.Column("Error", sa.Text(), nullable=True),
        sa.Column("PremiumSum", sa.Integer(), nullable=False),
        sa.Column("KASKOSum", sa.Integer(), nullable=False),
        sa.Column("DOSum", sa.Integer(), nullable=False),
        sa.Column("GOSum", sa.Integer(), nullable=False),
        sa.Column("NSSum", sa.Integer(), nullable=False),
        sa.Column("GAPSum", sa.Integer(), nullable=False),
        sa.Column("TotalFranchise", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("insurance_elt")
    # ### end Alembic commands ###
