"""Added payments_period in InsuranceElt Table

Revision ID: 2d2e71174561
Revises: 2f14fc68a92c
Create Date: 2024-12-14 14:29:32.011943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d2e71174561"
down_revision: Union[str, None] = "2f14fc68a92c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "insurance_elt", sa.Column("payments_period", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("insurance_elt", "payments_period")
    # ### end Alembic commands ###
